In [2]:
import numpy as np

## Comprendiendo los array de Numpy como matrices de números.

Dimensiones

In [3]:
#Print matriz de dimensiones n x m
def print_matrix(a: np.ndarray):
    for row in a.tolist():
        print(' '.join([str(x) for x in row]))

1 dimensión. Vector fila.

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.shape)
print(arr_1d)

(5,)
[1 2 3 4 5]


dimensión 2x3 (2 filas, 3 columnas)

In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.shape)
print_matrix(arr_2d)

(2, 3)
1 2 3
4 5 6


## Los array satisfacen propiedades!

Suma (Debe tener las mismas dimensiones)

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate the sum of the arrays
sum_array = arr1 + arr2

print(sum_array)

[5 7 9]


Multiplicación común

In [7]:
product_array = arr1 * arr2
print(product_array)

[ 4 10 18]


Producto Punto

In [8]:
matricial_product = np.dot(arr1, arr2)
print(matricial_product)

32


Transpuesta

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get the transpose of the array
arr_transpose = arr.transpose()



print("Array:")
print(arr)
print("array dimensions:")
print(arr.shape)

print("Transpose:")
print(arr_transpose)

print("Dimensions:")
print(arr_transpose.shape)

Array:
[[1 2 3]
 [4 5 6]]
array dimensions:
(2, 3)
Transpose:
[[1 4]
 [2 5]
 [3 6]]
Dimensions:
(3, 2)


Producto matricial

In [15]:
matrix_product = arr @ arr.T

print(matrix_product)

[[14 32]
 [32 77]]
